### ISSUE TITLE
[FR] Adjustable movement speed

### ISSUE THREAD

**Issue by almetica** [GoldenDelicios/world-pregen#1]
Hi!

Thank you for this datapack. We used it to prerender out server map, so that we could merge old maps into a new ones without havin ugly glitches near areas were people build something.

While running it, I saw that my computer was fast enough that it could run faster, since it was fast enough to render all chunks in time. Would it be possible to have some sort of movement speed that could be configured by the user, so that people could render the world faster/slower?

**Comment by GoldenDelicios** [comment]
Thank you for using the datapack!

This is a good suggestion, but it will likely require a redesign of the approach to implement it well. Essentially, I'd like the datapack to skip ahead once it can check and verify the chunks have been generated (e.g. by trying to summon an entity). This would mean reworking a few things like how to calculate the average speed to correctly estimate the remaining time.

It may be a while before I get a chance to look into this, so I'll leave this issue open and I'll try get to it whenever I next work on this.

**Comment by Romaq** [comment]
Ugh... if https://www.reddit.com/r/MinecraftCommands/comments/jqqvri/how_to_delay_commands_inside_a_function_for_a/ had a method I could just throw in, I'd have done it in the movement commands.

I *think* what is happening is that the datapack teleports me too fast to give the land generation time to actually spawn chunks, even if I'm only teleporting to the next chunk. Maybe if I throw in a delay that spins me in place by a count of degrees? It would be terribly dizzying if bothered to watch the screen, but I'd just not watch it.

**Comment by atyshka** [comment]
@Romaq  Any progress? I am try to pre generate a Terralith server, and Terralith takes a lot longer than normal terrain gen, so nothin is getting generated because the movement is too fast

**Comment by GoldenDelicios** [comment]
Thank you for your feedback guys. As of v1.3, the datapack adjusts its speed automatically, and will slow down or speed up based on whether the surrounding chunks are loaded.
