### ISSUE TITLE
Render/View Distance <5 chunks?

### ISSUE THREAD

**Issue by weeedy** [GoldenDelicios/world-pregen#10]
I used it on 1.17.1 - anyone also had some problems with render-distance <5 chunks?
Recommended render-distance would be a nice hint in Readme-File too, thanks you for your great work!

I also had to bring me in spectator mode manually, data pack brang me to creative mode.

Greetings Leo

**Comment by GoldenDelicios** [comment]
Thanks for your feedback!
This datapack requires a render distance of 5 or greater. I've added this information to the Readme.
I've also fixed the datapack not switching the player to spectator mode.
