### ISSUE TITLE
1.16 breaking the datapack

### ISSUE THREAD

**Issue by Thewolfs** [GoldenDelicios/world-pregen#2]
Hi,

I updated to 1.16 and the load command didn't fire and didn't create the scoreboard

The rest of the commands seem to work properly after I added the scoreboard

**Comment by GoldenDelicios** [comment]
I downloaded the datapack and used it in a fresh world to generate a 960x960 area in Minecraft 1.16.2 pre-3 and didn't run into any issues.

If this is still a problem, I'll need more specific steps to reproduce the issue, the exact game version, and whether you're running vanilla, Spigot, Paper, etc.

**Comment by GoldenDelicios** [comment]
Closing this as I've been unable to reproduce. Feel free to open a new ticket with steps to reproduce if you run into this issue again.
