### ISSUE TITLE
Advancement get: Remote Getaway

### ISSUE THREAD

**Issue by ColinTheShark** [GoldenDelicios/world-pregen#3]
I ran this datapack on my server I transferred from Vanilla to Paper and installed Dynmap, wanted to pre-gen terrain so I can have it in Dynmap already. Upon starting the script via `/function pregen:config`, it immediately gave me the advancement that I had to remove manually again. Is this advancement by accident or intentional?

Also, removed it with `/advancement revoke ColinShark from end/root` *(This removed 9 advancement, fully removing the full "End" branch from the Advancements menu)*.

---

Edit: I found [these lines](https://github.com/GoldenDelicios/world-pregen/blob/master/pregen/data/pregen/functions/start.mcfunction#L41-L46) that `setblock minecraft:end_gateway`. This triggers the advancement. Maybe add a check if the advancement was acquired before and if not automatically remove it again?

**Comment by GoldenDelicios** [comment]
You can gain many advancements or parts of advancements using this datapack just by virtue of visiting so many locations. Examples include Adventuring Time, We Need to Go Deeper, Hot Tourist Destinations, A Terrible Fortress, The City at the End of the Game, etc.

I won't be able to track every advancement and criteria given by the world generation process; I'd recommend either running `/advancement revoke @s everything` if you're generating a brand new world, using an alt account if you have one, or backing up your advancement file in `/world/advancements`
