### ISSUE TITLE
1.16.2 Unable to Verify

### ISSUE THREAD

**Issue by djayfresh** [GoldenDelicios/world-pregen#4]
Hello, 

I'm currently unable to get past the verification step after the first teleport to 0,0. My player enters into creative mode, and is teleported up to 200. My player then starts to fall, as the verify messages pass through chat, after 10 results in the failure. I took a look through the datapack and see the verify function calls failure after 10 attempts. I'm guessing it has something to do with the player falling even after entering creative mode. 

gamerule doMobSpawning false
gamerule doWeatherCycle false
gamerule doDaylightCycle false
gamerule doFireTick false

Minecraft: 1.16.2
Java: 1.8.0_211 64bit

Installed with MultiMC5.

**Comment by djayfresh** [comment]
Not sure what I did to get this working. I started doing TP commands by hand, then got super annoyed by how tedious that is lol. 
TP myself to 0 200 0. Hit [Start] again, and its working.

**Comment by GoldenDelicios** [comment]
This has been properly fixed in v1.2. Sorry for the delay, I'm not able to dedicate much time to maintaining my older datapacks. Let me know if you still run into this problem.
