### ISSUE TITLE
Solution for "Unable to verify" bug

### ISSUE THREAD

**Issue by bucketss** [GoldenDelicios/world-pregen#6]
> Not sure what I did to get this working. I started doing TP commands by hand, then got super annoyed by how tedious that is lol.
> TP myself to 0 200 0. Hit [Start] again, and its working.

-[source](https://github.com/GoldenDelicios/world-pregen/issues/4#issuecomment-683309715)

1. Enter creative mode
2. Start flying (double-tap your jump key)
3. */teleport @s 0 200 0*
4. */function pregen:config*
5. Configure and run the pre-generator

This seems to work in all dimensions.

I wanted to make a separate post because I'm sure alot of people missed that solution, and it worked perfectly for me.

**Comment by GoldenDelicios** [comment]
This has been properly fixed in v1.2. Thank you for sharing the workaround in the meantime.
I'll leave this open in case other changes to the game cause this issue to appear again.
