### ISSUE TITLE
Reduce the distance between the circles while pregenerate

### ISSUE THREAD

**Issue by BLACK4585** [GoldenDelicios/world-pregen#8]
Hey,

first thank you for your great Datapack! But my problem is that the individual circles are too far away from themselves. I've already increased the view Distance from the Server and also from my Game but there are still unloaded chunks. 
Is there a possiblity to add a function to set the width between the individual circles? Or if not, could you tell the file, where to set in in the source code?

Many thanks and have a nice day,
BLACK

![image](https://user-images.githubusercontent.com/71935902/134175137-19dbf253-d0bb-4c33-ac9a-b79e663ca141.png)

**Comment by GoldenDelicios** [comment]
Thank you for your feedback! The datapack should now adjust its speed to ensure all chunks are generated.
