### ISSUE TITLE
Missing info in README

### ISSUE THREAD

**Issue by mcailac** [GoldenDelicios/world-pregen#9]
Hi, thanks for this datapack. It helps a lot having my world generated for the rest of my game without lags because of the generation 😄 

I miss some information:
Can it be used on server? If yes what value to set for the render distance?
Same question for client side: what render distance to use? I don't know if there is a difference if we set 1 chunk or 32.

**Comment by GoldenDelicios** [comment]
Hello, thanks for using the datapack!
Yes the datapack can be used on a server. The minimum recommended render distance is 5 chunks.
I've updated README with this information.
